### ISSUE TITLE
cannot find any samples

### ISSUE THREAD

**Issue by touseefbsb** [Sergio0694/UICompositionAnimations#2]
looks like a useful library but can you please make a sample app in the repo? where all features can be seen? according to the SDK version, because I guess you have also included support with latest insiders SDK, i.e : creators fall update SDK. just a suggestion, that a proper sample app showing all the features with examples would make the most use of this library :) I was trying to put acrylic affect but where I can find the noise.png file?

**Comment by Sergio0694** [comment]
Hello @touseefbsb - thanks for your feedback!
As for your questions:

1) You're right, at the moment a sample app would be fine. The reason why there isn't one is that I originally created this library while working on my app [**OneLocker**](https://www.microsoft.com/store/apps/9nblggh3t7g3) and then I decided to publish it as a separate NuGet package. So I just haven't had the time to write a sample app too, as right now I'm also working on another side project. I might do something like that in the future, in the meantime check the code examples in the readme file!
2) You're right, the library supports every Windows 10 build from the 10.14393, right you'll have to manually check if a given effect is supported on your device depending on the kind of APIs it uses. A quick workaround for now: just try it out once, see if it works or if it throws an exception, then mark it as valid or not for your current build.
3) You'll have to create your own noise texture for the acrylic effect - it has to be a transparent PNG image with a white noise over it (I suggest to keep the overall image opacity low enough). You can use Paint.NET and the NoiseChoice plugin to create your own texture for the acrylic effect.

**Comment by touseefbsb** [comment]
thankyou for the response I can understand being a indie developer gives you less time for community projects :) but you still did a great job by publishing this library .

**Comment by Sergio0694** [comment]
Closing, as the library has also been updated a lot since this issue was first opened.
All the updated docs are in the `README.md` file, there are also code snippets there that showcase most of the available APIs.
