### ISSUE TITLE
Where is DoubleAnimation ??

### ISSUE THREAD

**Issue by AbdAlghaniAlbiek** [Sergio0694/UICompositionAnimations#20]
I searched for DoubleAnimation in this toolkit but I didn't found it?  Is there a alternative for it?
I know that I can use ChangePropertyAction and determine the property that I want make convert its value and get the animation that I want but it's good for me to see all my animation in one place

**Comment by Sergio0694** [comment]
This repo has been integrated with the [Windows Community Toolkit](https://learn.microsoft.com/en-us/windows/communitytoolkit/). See [AnimationBuilder](https://learn.microsoft.com/en-us/windows/communitytoolkit/animations/animationbuilder) and [AnimationSet](https://learn.microsoft.com/en-us/windows/communitytoolkit/animations/animationset) for docs on how to replace the previous APIs 🙂
