### ISSUE TITLE
Binding Tint to CustomAcrylicBrush fails with exception

### ISSUE THREAD

**Issue by Gh0s7** [Sergio0694/UICompositionAnimations#5]
Hi there,
I'm trying to create a `CustomAcrylicBrush` with current accent color as `Tint`, but I'm getting the following exception:

> Failed to assign to property 'UICompositionAnimations.Brushes.CustomAcrylicBrush.Tint'. [Line: 15 Position: 33]'

Here's my sample code:

    <brushes:CustomAcrylicBrush x:Key="InAppGrayAcrylicBrush"
                                BlurAmount="8"
                                FallbackColor="{ThemeResource SystemAccentColor}"
                                Mode="InAppBlur"
                                NoiseTextureUri="/Assets/Misc/Noise.png"
                                Tint="{ThemeResource SystemAccentColor}"
                                TintMix="0.6"
                                UnsupportedEffectFallbackColor="{ThemeResource SystemAccentColor}" />

Manually writing color's hex code works, but I need it to be bound via XAML (no code-behing please!).
Please note that the color seems correctly bound because I can see it in Visual Studio's Property window, still it fails at runtime.

EDIT:
Missed exception's type: **Windows.UI.Xaml.Markup.XamlParseException**

**Comment by Sergio0694** [comment]
Hello, thanks for your feedback. 
I'll look into this issue, for now you can try to use `{StaticResource SystemAccentColor}`, which seem to work fine (with the drawback that it won't be updated in real time if the user changes the accent color while the app is running.

**Comment by Sergio0694** [comment]
Hello @Gh0s7 - I've just published a new version of the NuGet package with a fix for the issue, `{ThemeResource}` bindings should now be working correctly 😄

**Comment by Gh0s7** [comment]
Grande, grazie per la fix istantanea! (non ha più senso usare l'inglese :p)
